language: node_js
node_js: 10.15.3
branches:
  only: master
cache: yarn
install: yarn
script:
- yarn build
- yarn test
- cd docs
- yarn
- yarn test
- yarn build
deploy:
- api_key:
    secure: OGUpA8E72fS8hYlpFPpOoAwRVUMxB3BgrcQWCeI8H9IpyJg3YxWOkAT0NO7EbHPhTyD81Wv03W6Wb4B02x2Wxxj3RzMKm3Vch+M1+LZBg8vHP//K5/v4NM742SnOzuBe/hZADSHQdSdn2Anawj998poXkDtPt80IlKEZ2+tEuVCZfh+DP4qHzL9hwmE2o1yon+9NXl8Bd1E4Pw2n152aNiqvk2eMJdRDMBlrH5nN/oN/UC6icLvDXTZYwTEDRXdNlR9HNqaD+J45KG6qmBVW9I69TZSz+4Y/7uiijaDKRJi+1gK4CfqhsvdWH74xJZpgxN11PZM84y3eGZQgF1JpNi4f0/JcsG2O3R1g/coyDAQFS3hk7klcNONN0h68wAocb4wCb4pg3nrPWrn7aD4YOaaDvJpwbFL1vl+WHTrJIGNSjgKbsu5/Bl2YZQzFzzv87vx6OqJmyS0uNI0kLEXCR3bwmOY4U38qih9yVlERojWKilLWK28j815L3t9lD0VGVHnYjmELQovRxr1OSLPXWMDjvRgYF2QQ7EMRegQeWmBonJkrnO3hp10uOckCLv91IYUObNLgP0g2UEwuD3zactEsjXYazNH/UD6SCI7SiaHoPTa7VIsFQpyHwjm11ROBG85gJJm8GP0Tjb1YOGLT3eZykP+fmHKaUXiwpuQlUPM=
  email: npmjs@charlesstover.com
  on:
    branch: master
  provider: npm
  skip_cleanup: true
- github-token:
    secure: YHTCjBwGiVZuTCJ2NQlPLiTYN59EB82X76l7/ipy3Vv0UtnILbbxXpSEiZpN9loC3wQ8xkqNuDqu4MqL4rNKt4UvVUmHmKusrPcw16JAJdwVtRiVXqy1W+wyBgnkfhTfT7eQ5zSlJxgHZ0iv/AWzA/z3HwfnMEAJM0fFChIzJWjXJ0J/lg4lswX3XJLjpNFPjut3XCKILr9x7N9UtGdqVEJgTdvOpm6jElyJJig5Aw3n23+LE/TWCSzIbbB5xT2W6Mhc80vuXeCWRFD2Otygiu+YNICiCARV3EL2rBcIIjKfX7Vuxru42TeuRMNaF57ru1F7dA/8bGHao33ARDdrG1ynNy0DRI1QL7N5cXEaGNuOhl0+zM1r+zsaF7CpqLr/WlcD+UcqFK7YSzgPpVRzvKCU2CzRD2J8cH+HD3P9Nkapj3wvQvvP25hXcyL9Ib4OXslSDCFk1lOeGb8Y8W7X43UOHe3RMkW9sPZNdCzYxwjTjs1pdtnk6QlBLvfIJ5q4o+AvcyOYxkaZQrzZwazDNzOP2PEUQ0MsV7hZWYeSH7r3H3KQR9Ne+uh/2Uy5/3X8JIn1cgz+DP+5FhpQOhWUVg696gEdjFCWSMXDUD2+r1+1pq/bK1IiD7gj59J9FhaonWlwWqCvvk35OtebbrT6HIUhGqvyA/tGrYMYKFI+0DE=
  keep-history: true
  local-dir: build
  on:
    branch: master
  provider: pages
  skip-cleanup: true
  target-branch: gh-pages
